language: python
python: '3.6'
install:
  - pip install --upgrade pip
  - pip install --process-dependency-links -e .
  - pip install -r test-requirements.txt
env:
  - TEST_ENV=travis
script:
  - flake8 .
  - py.test
after_success:
  - coveralls
